[build]
  publish = "."
  
[build.environment]
  NODE_ENV = "production"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com https://unpkg.com https://elevenlabs.io https://*.elevenlabs.io; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://unpkg.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://elevenlabs.io https://*.elevenlabs.io; frame-src https://elevenlabs.io https://*.elevenlabs.io;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# HTML caching
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Redirects for clean URLs
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/uomini"
  to = "/pages/per-uomini.html"
  status = 301

[[redirects]]
  from = "/familiari"
  to = "/pages/per-familiari.html"
  status = 301

[[redirects]]
  from = "/professionisti"
  to = "/pages/per-professionisti.html"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/pages/contatti.html"
  status = 301

[[redirects]]
  from = "/resources"
  to = "/pages/risorse.html"
  status = 301

# 404 fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Form handling (Netlify Forms)
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = true
[build.processing.js]
  bundle = false
  minify = true
[build.processing.html]
  pretty_urls = true
  canonical_urls = true